// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDupT3iY1MazktaW5Tf_ijBENbTNjDXp-Y',
    appId: '1:566400543574:web:6237fdb7c3fd58a859c4f7',
    messagingSenderId: '566400543574',
    projectId: 'astute-contracts',
    authDomain: 'astute-contracts.firebaseapp.com',
    storageBucket: 'astute-contracts.firebasestorage.app',
    measurementId: 'G-LBZJF229VP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOeGOHOQcwOuH2aYq8HXRSUqLBqYWhuUM',
    appId: '1:566400543574:android:fa75a0f20f3e4c6b59c4f7',
    messagingSenderId: '566400543574',
    projectId: 'astute-contracts',
    storageBucket: 'astute-contracts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvZh63zh6VyVElwNobGTqJZjAqskr8Wpo',
    appId: '1:566400543574:ios:c1dfea63c2fd0be759c4f7',
    messagingSenderId: '566400543574',
    projectId: 'astute-contracts',
    storageBucket: 'astute-contracts.firebasestorage.app',
    iosBundleId: 'com.example.astute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvZh63zh6VyVElwNobGTqJZjAqskr8Wpo',
    appId: '1:566400543574:ios:c1dfea63c2fd0be759c4f7',
    messagingSenderId: '566400543574',
    projectId: 'astute-contracts',
    storageBucket: 'astute-contracts.firebasestorage.app',
    iosBundleId: 'com.example.astute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDupT3iY1MazktaW5Tf_ijBENbTNjDXp-Y',
    appId: '1:566400543574:web:55c7b6fbf5266d4a59c4f7',
    messagingSenderId: '566400543574',
    projectId: 'astute-contracts',
    authDomain: 'astute-contracts.firebaseapp.com',
    storageBucket: 'astute-contracts.firebasestorage.app',
    measurementId: 'G-ENC5GQ7T5D',
  );

}