// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBldL3_zaOOBaX2WlrUT1JHROKrKdgTOX4',
    appId: '1:1047724374342:web:3300a15f8ae5a0919d0d47',
    messagingSenderId: '1047724374342',
    projectId: 'astute-2025',
    authDomain: 'astute-2025.firebaseapp.com',
    storageBucket: 'astute-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5jzASt1CxGjNFphQB1w0aniXb14YF_nw',
    appId: '1:1047724374342:android:93b7ec5362b706fb9d0d47',
    messagingSenderId: '1047724374342',
    projectId: 'astute-2025',
    storageBucket: 'astute-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZvD9ZC3SdcNzhFScz-qTXBYSXgw-Jm3w',
    appId: '1:1047724374342:ios:890a697ce5414c059d0d47',
    messagingSenderId: '1047724374342',
    projectId: 'astute-2025',
    storageBucket: 'astute-2025.firebasestorage.app',
    androidClientId: '1047724374342-35sk7gvujkagdh49u7r49qju96dtvmho.apps.googleusercontent.com',
    iosClientId: '1047724374342-bpnftben5e939kkd5cfeie3ghq4se7oq.apps.googleusercontent.com',
    iosBundleId: 'com.example.astute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZvD9ZC3SdcNzhFScz-qTXBYSXgw-Jm3w',
    appId: '1:1047724374342:ios:890a697ce5414c059d0d47',
    messagingSenderId: '1047724374342',
    projectId: 'astute-2025',
    storageBucket: 'astute-2025.firebasestorage.app',
    androidClientId: '1047724374342-35sk7gvujkagdh49u7r49qju96dtvmho.apps.googleusercontent.com',
    iosClientId: '1047724374342-bpnftben5e939kkd5cfeie3ghq4se7oq.apps.googleusercontent.com',
    iosBundleId: 'com.example.astute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBldL3_zaOOBaX2WlrUT1JHROKrKdgTOX4',
    appId: '1:1047724374342:web:71a5a90c8602ba8a9d0d47',
    messagingSenderId: '1047724374342',
    projectId: 'astute-2025',
    authDomain: 'astute-2025.firebaseapp.com',
    storageBucket: 'astute-2025.firebasestorage.app',
  );
}